### ISSUE TITLE
Rule "HTTP OUTBOUND - Does NOT have retry logic" description needs a fix

### ISSUE THREAD

**Issue by abmogal96** [Integral-Zone/falcon-scan-extension#1]
Code snippet in the "HTTP OUTBOUND - Does NOT have retry logic" rule description should be correctly formatted.

` <until-successful maxRetries="5" doc:name="Until Successful">
<http:request config-ref="HTTP_Listener_Configuration_TestM" path="" method="" doc:name="HTTP"/>
</until-successful>`

**Comment by vedanth-kr** [comment]
Issue has been fixed in v0.1.0
