### ISSUE TITLE
On the fly results View

### ISSUE THREAD

**Issue by izchethan** [Integral-Zone/falcon-scan-extension#2]
**Is your feature request related to a problem? Please describe.**
In the on the fly results view, it currently has a See button to view the rule that caused the issue.

**Describe the solution you'd like**
Either a simple icon or may be a feature where if you single/double click it auto opens the rule description would be useful.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by vedanth-kr** [comment]
Issue has been fixed in v0.1.0
